server:
  port: 8080
  servlet:
    context-path: /dev

my1:
  age: 40
  name: Deane

spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true&useSSL=false
    username: deane
    password: deane123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database: mysql

mybatis:
  mapper-locations: classpath:Mybatis/*.xml
  config-location: classpath:mybatis-config.xml
  type-aliases-package: com.deane.entity
